import random, os, string, requests, json

class account:
    """
    Developed by Trent
        
    A discord library made for easily interacting with discord's API in order to mess around with a user.

    Currently supported features
    ----------------------------
    GET:
        NewHeaders
        RandomNonce
        RandomCookies
        PaymentMethods
        UserChannelID
        Name
        Bio
        Id
        Email
    SET:
        SetEmail
        SetName
        SetBio
        SetHypesquad
        SetStatus
    ACTIONS:
        MakeRequest
        AddFriend
        RemoveFriend
        SendMessage
        ScrapeMessages
        PurgeMessages
        JoinGuild
        LeaveGuild
    """
    def __init__(self, token: str, proxies: dict|None):
        self.token = token
        self.proxies = proxies
        self.get = self._GetMethods(token, proxies)
        self.set = self._SetMethods(token, proxies)
        self.actions = self._ActionMethods(token, proxies)

    class _GetMethods():
        def __init__(self, token, proxies):
            self.token=token
            self.proxies=proxies
        def NewHeaders(self, refer: str=None) -> dict:
            """
            Grabs a set of new, unique headers for use in a discord request. These headers don't lock your account. Can be accessed via account.get.NewHeaders().

            Args:
                refer (optional): Overwrite the referer URL in the headers.
            Returns:
                headers (dict): Headers used in most requests that shouldn't lock accounts.
            """
            if refer == None:
                refer = "https://discord.com/channels/@me"
            cookies = [
                ("locale", "en-GB"),
                ("__dcfduid", self.RandomCookies(43)),
                ("__sdcfduid", self.RandomCookies(96)),
                ("__stripe_mid", "-".join(map(self.RandomCookies, (18, 4, 4, 4, 18)))),
                ("__cfruid", self.RandomCookies(40) + "-" + "".join(random.choice(string.digits) for _ in range(10))),
            ]
            return {
                "accept": "*/*",
                "accept-encoding": "gzip, deflate",
                "accept-language": "en-GB",
                "origin": "https://discord.com",
                "sec-fetch-dest": "empty", 
                "sec-fetch-mode": "cors",
                "sec-fetch-site": "same-origin",
                "content-type": "application/json",
                "authorization": self.token,
                "referer": refer,
                "cookie": "; ".join(map("=".join, cookies)),
                "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) discord/0.1.9 Chrome/83.0.4103.122 Electron/9.4.4 Safari/537.36",
                "x-super-properties": "eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRGlzY29yZCBDbGllbnQiLCJyZWxlYXNlX2NoYW5uZWwiOiJzdGFibGUiLCJjbGllbnRfdmVyc2lvbiI6IjAuMS45Iiwib3NfdmVyc2lvbiI6IjEwLjAuMTc3NjMiLCJvc19hcmNoIjoieDY0Iiwic3lzdGVtX2xvY2FsZSI6ImVuLVVTIiwiY2xpZW50X2J1aWxkX251bWJlciI6OTM1NTQsImNsaWVudF9ldmVudF9zb3VyY2UiOm51bGx9",
                "x-debug-options": "bugReporterEnabled",
            }
        def RandomNonce(self) -> bytes:
            """
            Generates a random nonce for use in certain requests. Not often used.

            Returns:
                nonce (bytes): Random unique bytes with a length of 16
            """
            return os.urandom(16).hex()[16:]
        def RandomCookies(self, length: int) -> bytes:
            """
            Generates a random hex string for use in request cookies. Can be accessed with account.randomCookies().

            Args:
                length (int): The length of the randomly generated bytes object after being converted to hex.
            Returns:
                cookies (bytes): Cookies for request headers.
            """
            return os.urandom(length).hex()[length:]
        def PaymentMethods(self) -> requests.Response:
            """
            Gets the payment methods of the user's account.

            Returns:
                response (requests.Response): The request's response.
            """
            return requests.get("https://discord.com/api/v9/users/@me/billing/payment-sources", headers=self.NewHeaders()).json()
        def UserChannelID(self, userid: str|int) -> requests.Response:
            """
            Gets a discord user's DM channel ID.
            
            Args:
                userid (str|int): The ID of the user to get the channel ID of.
            Returns:
                response (requests.Response): The request's response.
            """
            return requests.post('https://discord.com/api/v9/users/@me/channels', json = {'recipients': [str(userid)]}, headers={"authorization": self.token}).json()['id']
        def _me(self):
            return requests.get("https://discord.com/api/v9/users/@me", headers = self.NewHeaders()).json()
        def Name(self) -> str:
            """
            Gets the name of the discord account

            Returns:
                name (str): The account's name
            """
            return self._me["username"]
        def Bio(self) -> str:
            """
            Gets the bio of the discord account

            Returns:
                name (str): The account's bio
            """
            return self._me["bio"]
        def Id(self) -> str:
            """
            Gets the id of the discord account

            Returns:
                name (str): The account's id
            """
            return self._me["id"]
        def Email(self) -> str:
            """
            Returns the discord account's email address.

            Returns:
                name (str): The account's email
            """
            return self._me["email"]
        def Hypesquad(self) -> dict:
            house_id = 0
            house_name = ""
            return {"house_id": house_id, "house_name": house_name}
    class _SetMethods(_GetMethods):
        def __init__(self, token, proxies):
            self.token=token
            self.proxies=proxies
        def MakeRequest(self, json: dict, **kwargs) -> requests.Response:
            """
            A method used to quickly and easily make a request. Not recommended for use outside of current methods, use your own requests if need be.

            Args:
                json (dict): The json provided to the request.
                content (optional): Pass content to the request.
                headers (optional): Overwrite headers with your own, uses get.NewHeaders if passed.
            Returns:
                response (requests.Response): The request's response.
            """
            content = kwargs.get("content", None)
            if kwargs.get("headers", None) == None:
                headers = self.NewHeaders(kwargs.get("referer", None))
            else:
                headers = {
                    "authorization": self.token
                }
            url = kwargs.get("url", "https://discord.com/api/v9/users/@me")
            if kwargs.get("type", "PATCH").upper():
                r = requests.patch(url, json = json, headers = headers, proxies = self.proxies)
            elif kwargs.get("type", "POST").upper():
                r = requests.post(url, json = json, headers = headers, proxies = self.proxies)
            elif kwargs.get("type", "GET").upper():
                r = requests.get(url, json = json, headers = headers, proxies = self.proxies)
            elif kwargs.get("type", "PUT").upper():
                r = requests.put(url, json = json, headers = headers, proxies = self.proxies)
            elif kwargs.get("type", "DELETE").upper():
                r = requests.delete(url, json = json, headers = headers, proxies = self.proxies)

            return r
        def SetEmail(self, password: str, newAddress: str) -> dict:
            """
            Sets the email of the account, but requires you to know the password. A new address should also be provided.

            Args:
                password (str): The account's current password, required for email changing.
                newAddress (str): The new email for the discord account.
            Returns:
                response (dict): A dictionary containing the email, password and token
            """
            password = password
            r = self.MakeRequest({"email": newAddress, "password": password})
            s = requests.post("https://discord.com/api/v9/auth/verify/resend", headers = self.NewHeaders(), proxies = self.proxies)
            print(f"Verification email sent, check {newAddress}")
            return {
                "email": newAddress,
                "password": password,
                "token": self.token
            }
        def SetName(self, password: str, newName: str) -> requests.Response:
            """
            Set the discord account's username, requires the password and a new username.

            Args:
                password (str): The current password of the account.
                newName (str): The new username for the account.
            Returns:
                response (requests.Response): The request's response.
            """
            return self.MakeRequest({"password": password, "username": newName}, type="PATCH")
        def SetBio(self, newBio: str) -> requests.Response:
            """
            Set the account bio for the discord account.

            Args:
                newBio (str): The new bio that will be set.
            Returns:
                response (requests.Response): The request's response.
            """
            return self.MakeRequest({"bio": newBio}, type="PATCH")
        def SetHypesquad(self, hypesquad: int) -> requests.Response:
            """
            Sets the account's hypesquad team using an integer or text

            Args:
                hypesquad (int|str): Numbers 1-3 as in 
                                     - Brilliance is 1
                                     - Bravery is 2
                                     - Balance is 3
            Returns:
                response (requests.Response): The request's response.
            """
            if type(hypesquad) == int():
                assert hypesquad in range(1,3)
            elif type(hypesquad) == str():
                assert hypesquad.lower() in ("bravery", "brilliance", "balance")
                translations = {
                    "bravery": 2,
                    "brilliance": 1,
                    "balance": 3
                }
                hypesquad = translations["hypesquad"]
            return requests.post("https://discord.com/api/v9/hypesquad/online", json={"house_id": hypesquad}, headers=self.NewHeaders())
        def SetStatus(self, status: str) -> requests.Response:
            """
            Sets the account's status on discord to online, dnd, invisible or idle

            Args:
                Status (str): The status to set the account to, accepts (online, dnd, invisible or idle)
            Returns:
                response (requests.Response): The request's response.
            """
            assert status in ["online", "dnd", "invisible", "idle"]
            return requests.patch("https://discord.com/api/v9/users/@me/settings", json={"status": status}, headers=self.NewHeaders())
    class _ActionMethods(_SetMethods, _GetMethods):
        def __init__(self, token, proxies):
            self.token=token
            self.proxies=proxies
        def MakeRequest(self, json: dict, **kwargs) -> requests.Response:
            """
            A method used to quickly and easily make a request. Not recommended for use outside of current methods, use your own requests if need be.

            Args:
                json (dict): The json provided to the request.
                content (optional): Pass content to the request.
                headers (optional): Overwrite headers with your own, uses get.NewHeaders if passed.
            Returns:
                response (requests.Response): The request's response.
            """
            content = kwargs.get("content", None)
            if kwargs.get("headers", None) == None:
                headers = self.NewHeaders(kwargs.get("referer", None))
            else:
                headers = {
                    "authorization": self.token
                }
            url = kwargs.get("url", "https://discord.com/api/v9/users/@me")
            if kwargs.get("type", "PATCH").upper():
                r = requests.patch(url, json = json, headers = headers, proxies = self.proxies, content=content)
            elif kwargs.get("type", "POST").upper():
                r = requests.post(url, json = json, headers = headers, proxies = self.proxies, content=content)
            elif kwargs.get("type", "GET").upper():
                r = requests.get(url, json = json, headers = headers, proxies = self.proxies, content=content)
            elif kwargs.get("type", "PUT").upper():
                r = requests.put(url, json = json, headers = headers, proxies = self.proxies, content=content)
            elif kwargs.get("type", "DELETE").upper():
                r = requests.delete(url, json = json, headers = headers, proxies = self.proxies, content=content)

            return r
        def AddFriend(self, **kwargs) -> requests.Response:
            """
            Sends a friend request to the provided user.

            Args:
                friendid (str): The user id of the user to remove as a friend
                tag (optional): Formatted as {'name': USERNAME, 'discriminator': DISCRIMINATOR}
            Returns:
                response (requests.Response): The request's response.
            """
            tag = kwargs.get("tag", None)
            username, discriminator = None,None
            headers = {
                "accept": "/",
                "accept-encoding": "gzip, deflate, br",
                "accept-language": "en-US,en-CH;q=0.9,en-GB;q=0.8",
                "authorization": self.token,
                "content-length": "0",
                "origin": "https://discord.com",
                "referer": "https://discord.com/channels/@me",
                "sec-fetch-dest": "empty",
                "sec-fetch-mode": "cors",
                "sec-fetch-site": "same-origin",
                "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) discord/1.0.669 Chrome/91.0.4472.164 Electron/13.6.6 Safari/537.36",
                "x-debug-options": "bugReporterEnabled",
                "x-discord-locale": "hu",
                "x-super-properties": "eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRGlzY29yZCBDbGllbnQiLCJyZWxlYXNlX2NoYW5uZWwiOiJjYW5hcnkiLCJjbGllbnRfdmVyc2lvbiI6IjEuMC42NjkiLCJvc192ZXJzaW9uIjoiMTAuMC4xOTA0MyIsIm9zX2FyY2giOiJ4NjQiLCJzeXN0ZW1fbG9jYWxlIjoiZW4tVVMiLCJjbGllbnRfYnVpbGRfbnVtYmVyIjoxMzMwOTgsImNsaWVudF9ldmVudF9zb3VyY2UiOm51bGx9"
            }
            if tag == None:
                user_id = kwargs.get("userid", None)
                if user_id == None:
                    print("[ERROR] addFriend encountered a severe error! Check returned value for error.")
                    return {"error": "UserID provided: "+{user_id}+" - if the value to the left is 'None' then pass 'userid=<ID>' to the argument"}
                headersv2 = {'authorization': 'NzcwMzUyODYyNzMwNzgwNzI0.GGVjF-.JZxlW7GiGnH273XY6zxKsw4KAzfsXHmBuOUO1A'}
                send = requests.get(f"https://discord.com/api/v9/users/{str(user_id)}", headers=headersv2) 

                b = send.json()
                username = b["username"]
                discriminator = b["discriminator"]
            else:
                username = tag["username"]
                discriminator = tag["discriminator"]

            url = "https://discord.com/api/v9/users/@me/relationships"
            body = {"username": username, "discriminator": discriminator}
            return requests.post(url, headers=headers, json=body)
        def RemoveFriend(self, friendid: str) -> requests.Response:
            """
            Remove a user as a friend.

            Args:
                friendid (str): The user id of the user to remove as a friend.
            Returns:
                response (requests.Response): The request's response.
            """
            return self.actions.MakeRequest({}, type="DELETE", url=f"https://discord.com/api/v9/users/@me/relationships/{friendid}")
        def SendMessage(self, message: str, channelid: str|int) -> requests.Response:
            """
            Send a message into a provided channel.
            
            Args:
                message (str): The message for the user to send.
                channelid (str|int): The id of the channel to send the message into. If it is a DM, use getUserChannelID for the DM's channel id.
            Returns:
                response (requests.Response): The request's response.
            """
            return requests.post(f"https://discord.com/api/v9/channels/{str(channelid)}/messages", headers = {"authorization": self.token}, data={"content": message})
        def ScrapeMessages(self, channelid: str|int, limit: str|int) -> list:
            """
            Scrape all the messages from a channel into a list of dict values.

            Args:
                channelid (str|int): The ID of the channel to scrape messages from.
                limit (str|int): The amount of messages to scrape from a channel.
            Returns:
                response (dict[]): A list of scraped messages.
            """
            messages = requests.get(f"https://discord.com/api/v9/channels/{str(channelid)}/messages?limit={str(limit)}", headers=self.NewHeaders()).json()
            total = []
            for eachMessage in range(len(messages)):
                msg = messages[eachMessage]
                total.append({
                    "author": {msg["author"]["id"]},
                    "content": msg["content"],
                    "id": msg["id"]
                })
            return total
        def PurgeMessages(self, channelid: str) -> list:
            """
            Purge all the account's messages from a channel.

            Args:
                channelid (str): The ID of the channel to purge messages from.
            Returns:
                response (requests.Response[]): The list of purged messages
            """
            purgedResponse = []
            messages = self.actions.ScrapeMessages(channelid)
            for i in messages:
                print(i["author"], self.Id())
                print(i["id"])
                if i["author"] == {self.Id()}:
                    purgedResponse.append(requests.delete(f"https://discord.com/api/v9/channels/{channelid}/messages/{i['id']}", headers=self.NewHeaders()))
            return purgedResponse
        def JoinGuild(self, inviteCode: str) -> requests.Response:
            """
            Join a guild using a provided invite link.
            
            Args:
                inviteCode (str): The invite code for the guild.
            Returns:
                response (requests.Response): The request's response.
            """
            if "discord.gg" in inviteCode:
                inviteCode = inviteCode.split(".gg/")[1]
            headers = self.NewHeaders()
            headers["x-context-properties"] = "eyJsb2NhdGlvbiI6Ik1hcmtkb3duIExpbmsifQ=="
            return requests.post(f"https://discord.com/api/v9/invites/{inviteCode}", headers=headers, json={})
        def LeaveGuild(self, guildid: str|int) -> requests.Response:
            """
            Leave a guild using the guild's ID.

            Args:
                guildid (str|int): The ID of the guild to leave.
            Returns:
                response (requests.Response): The request's response.
            """
            headers = self.NewHeaders()
            return requests.delete(f"https://discord.com/api/v9/users/@me/guilds/{str(guildid)}", headers=headers)
        def CreateGroupChat(self, users: list):
            """
            Create a group chat using a list of user ids

            Args:
                users (list): A list of user ids as strings such as ["ID", "ID", "ID"]
            Returns:
                response (requests.Response): The request's response.
            """
            headers = self.NewHeaders()
            recipients = []
            for eachUser in users:
                recipients.append(str(eachUser))
            return requests.post('https://discord.com/api/v9/users/@me/channels', json = {'recipients': recipients}, headers={"authorization": self.token}).json()['id']






token = "NzcwMzUyODYyNzMwNzgwNzI0.Gp_iq7._J_a2fvq3wPfKIXKhvGvZrLsLMk615TslVJHIM"
acc = account(token,None)
